#!/bin/Rscript
FROM ubuntu:16.04

# Install essential unix packages and dependencies:
RUN apt-get update -y --fix-missing
RUN apt-get install -y build-essential \
    wget \
    tar
RUN apt-get update -y --fix-missing
RUN apt-get install -y r-base


# Download and install SIAMCAT
ENV SIAMCAT_URL "https://git.embl.de/grp-zeller/SIAMCAT/repository/cwl-workflow/archive.tar.gz"
RUN cd /usr/local/ \
    && wget -O SIAMCAT.tar.gz ${SIAMCAT_URL} \
    && tar -xvzf SIAMCAT.tar.gz \
    && rm SIAMCAT.tar.gz \
    && mv ./SIAMCAT* ./SIAMCAT \
    && Rscript ./SIAMCAT/Rscript_flavor/00_setup.r ./SIAMCAT.tar.gz
ENV PATH="/usr/local/siamcat/Rscript_flavor:${PATH}"